[[params.meta]]
favicon = false
svg = false

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
title = "ODA"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "news"
name = "Обновления"
url = "/news/"
weight = 20


[[languages.en.menu.main]]
identifier = "widgets"
name = "Виджеты"
url = "/widgets/"
weight = 20

[[languages.en.menu.main]]
identifier = "enroll"
name = "Как подключить"
url = "/enroll/"
weight = 30

[[languages.en.menu.main]]
identifier = "login"
name = "Войти"
url = "https://widgets.oda.digital/"
weight = 50

[markup.goldmark.renderer]
unsafe = true

[params.paige]
style = """
    #paige-collections,
    #paige-sections,
    #paige-reading-time,
    #paige-credit,
    #paige-breadcrumbs,
    #paige-pages {
      display: none;
    }
    .nav-pills a.nav-link.active {
      background-color: #684aff;
    }
    .paige-icon a{
      color: #684aff;
    }
"""

[params.paige.search]
hide_page = true

[params.paige.analytics.yandex]
account_id = "96296405"

[params.paige.analytics.clarity] # See https://clarity.microsoft.com
account_id = "mm1viw59qq"
